apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationServer
metadata:
  name: create-customer-details-rest
spec:
  designerFlowsOperationMode: disabled
  license:
    accept: true
    license: L-KSBM-C37J2R
    use: CloudPakForIntegrationNonProduction
  replicas: 1
  router:
    timeout: 120s
  service:
    endpointType: https
  useCommonServices: true
  version: 12.0.1.0-r3
  adminServerSecure: true
  pod:
    containers:
      runtime:
        image: TO BE REPLACE BY PROMOTIONS PIPELINES
        imagePullPolicy: Always
  configurations:
    - ibm-rest-dbparms.txt
    - ibm-rest-serverconf.yaml
    - ibm-rest-policy
    - ibm-ace-server.jks
    - ibm-ca.jks
